# Generated by Django 5.1.1 on 2025-01-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kniznica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kniznica.autor'),
        ),
        migrations.AddField(
            model_name='kniha',
            name='miesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kniznica.miesto'),
        ),
        migrations.AddField(
            model_name='kniha',
            name='vydavatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kniznica.vydavatel'),
        ),
    ]
